# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Update fastlane
update_fastlane

default_platform(:ios)


platform :ios do
    desc "Build binary"
    lane :build do
        get_certificates           # invokes cert
        get_provisioning_profile   # invokes sigh
        generate_icons
        if lane_context[SharedValues::LANE_NAME] == 'ios beta'
            #TODO we need to define how we deal with versioning for both beta and release deployments
            increment_build_number(
                xcodeproj: './LiqualityMobile.xcodeproj',
                build_number: latest_testflight_build_number + 1
            )
            # requires imagemagick (brew install imagemagick)
            add_badge(
                # shield: "Version-0.0.1-blue",
                glob: "/LiqualityMobile/Images.xcassets/AppIcon.appiconset/*.png"
            )
        end
        build_app(workspace: "LiqualityMobile.xcworkspace", scheme: "LiqualityMobile")
    end

    desc "Push a new beta build to TestFlight"
    lane :beta do
        build
        upload_to_testflight(skip_waiting_for_build_processing: true) #pilot
    end
end
